(deftheme Candybread
  "Created 2023-04-15.")

(custom-theme-set-faces
 'Candybread
 '(default ((t (:family "SourceCodeVF" :foundry "ADBO" :width normal :height 128 :weight normal :slant normal :underline nil :overline nil :extend t :strike-through nil :box nil :inverse-video nil :foreground "medium orchid" :background "peach puff" :stipple nil :inherit (default)))))
 '(cursor ((t (:inverse-video t :foreground "#262626" :background "#F8F8F2"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#75715E"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#99CCFF"))))
 '(highlight ((t (:background "#49483E"))))
 '(region ((t (:extend t :background "#49483E" :inherit (highlight)))))
 '(shadow ((t (:foreground "#75715E"))))
 '(secondary-selection ((t (:background "#3E3D31" :inherit (region)))))
 '(trailing-whitespace ((t (:background "#FF6666"))))
 '(font-lock-builtin-face ((t (:weight normal :foreground "#FF6666"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#75715E"))))
 '(font-lock-comment-face ((t (:foreground "#75715E"))))
 '(font-lock-constant-face ((t (:foreground "#AE81FF"))))
 '(font-lock-doc-face ((t (:foreground "yellow green"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "#A6E22E"))))
 '(font-lock-keyword-face ((t (:weight normal :foreground "#FF6666"))))
 '(font-lock-negation-char-face ((t (:foreground "salmon" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#FF6666"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :foreground "#AE81FF"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "salmon1" :weight normal))))
 '(font-lock-string-face ((t (:foreground "salmon2"))))
 '(font-lock-type-face ((t (:slant normal :foreground "#99CCFF"))))
 '(font-lock-variable-name-face ((t (:foreground "#FD971F"))))
 '(font-lock-warning-face ((t (:weight bold :slant italic :underline (:color foreground-color :style line) :foreground "#FD971F"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#99CCFF"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#AE81FF"))))
 '(fringe ((t (:foreground "#F8F8F2" :background "#262626"))))
 '(header-line ((t (:box (:line-width (1 . 1) :color "#64645E" :style unspecified) :foreground "#F8F8F0" :background "#49483E"))))
 '(tooltip ((t (:foreground "#262626" :background "#FFFACE" :inherit (default)))))
 '(mode-line ((t (:box (:line-width (1 . 1) :color "#64645E" :style unspecified) :foreground "#F8F8F0" :background "#49483E"))))
 '(mode-line-buffer-id ((t (:foreground "maroon" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((supports :box t) (class color) (min-colors 88)) (:box (:line-width (2 . 2) :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width (1 . 1) :color "#64645E" :style unspecified) :foreground "#75715E" :background "#262626"))))
 '(isearch ((t (:foreground "#262626" :background "#E6DB74" :inherit (region)))))
 '(isearch-fail ((t (:weight bold :foreground "#262626" :background "#ff6666"))))
 '(lazy-highlight ((t (:background "#3E3D31" :inherit (highlight)))))
 '(match ((t (:weight bold :foreground "#262626" :background "#E6DB74"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'Candybread)
